import React from "react";

import { Toaster } from "@/components/ui/sonner";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/layout/AppShell";
import { PageHeader } from "@/components/layout/PageHeader";
import { SectionNav } from "@/components/layout/SectionNav";
import { ConfirmActionDialog } from "@/components/common/ConfirmActionDialog";
import { LegacyDialog } from "@/components/common/LegacyDialog";
import { ModuleIndexPage } from "@/features/modules/ModuleIndexPage";
import { ModuleHomePage } from "@/features/modules/ModuleHomePage";
import { AdminPanel } from "@/features/admin/AdminPanel";
import { NoteGroupCreate } from "@/features/note-groups/NoteGroupCreate";
import { ReadingDialog } from "@/features/reading/ReadingDialog";
import { ReviewDialog } from "@/features/review/ReviewDialog";
import { SubjectIndexPage as SubjectIndexRouteContent } from "@/features/subjects/SubjectIndexPage";
import { SubjectManagementPanel } from "@/features/subjects/SubjectManagementPanel";
import { ConceptScopeContent, NoteGroupScopeContent } from "@/features/study-scope/StudyScopeContent";
import { TutorChatDialog } from "@/features/chat/TutorChatDialog";
import { StudyAppGlobalDialogs } from "@/features/app-shell/StudyAppGlobalDialogs";
import { StudyAppMainContent } from "@/features/app-shell/StudyAppMainContent";
import { StudyAppReadingDialog } from "@/features/app-shell/StudyAppReadingDialog";
import { StudyAppReviewOverlay } from "@/features/app-shell/StudyAppReviewOverlay";
import { StudyAppTutorChatOverlay } from "@/features/app-shell/StudyAppTutorChatOverlay";
import {
  appShellClasses,
  generationWorkflowStageLabel,
  generationWorkflowStatusLabel,
  generationWorkflowTitle
} from "@/features/app-shell/appShellUi";
import { countWords, formatCreatedAt, getNoteGroupStatusMeta } from "@/lib/format";
import { renderCleanedMarkdown, renderMarkdownBlocks } from "@/lib/text-rendering";

const {
  panel: panelClass,
  primaryButton: primaryButtonClass,
  outlineButton: outlineButtonClass,
  destructiveOutlineButton: destructiveOutlineButtonClass,
  buttonRow: buttonRowClass,
  badge: badgeClass,
  mutedText: mutedTextClass,
  errorText: errorTextClass
} = appShellClasses;

export function StudyAppView({ model }) {
  const {
    authActions,
    autoAdditionalInstructions,
    autoCreateError,
    autoCreateLoading,
    autoJobActionId,
    autoJobsByNoteGroupId,
    autoRawText,
    canCreateSubjects,
    canDeleteSubject,
    canEditCurrentCards,
    canMaintainSubject,
    canManageSelectedSubject,
    canReorderNoteGroups,
    canUseProtectedActions,
    cancelReviewDelete,
    chatCardCache,
    chatCardError,
    chatCardId,
    chatCardLoading,
    chatError,
    chatInput,
    chatListRef,
    chatLoading,
    chatMessages,
    chatView,
    chipFilterIds,
    chipFilterValue,
    chipOptions,
    clearMindMapDrilldown,
    closeQuestionFocus,
    confirmAction,
    confirmReviewDelete,
    currentReviewCard,
    currentUserProfile,
    dragOverNoteGroupId,
    draggedNoteGroupId,
    editingQuestionCard,
    editingQuestionCardId,
    editingStudyCard,
    editingStudyCardId,
    editingSubjectId,
    effectiveCleanedText,
    endReview,
    filteredStudyCards,
    focusCardType,
    focusMasteryScore,
    focusMasteryTier,
    focusQuestionCard,
    formatDueAt,
    formatReviewAt,
    generationWorkflowsByNoteGroupId,
    getSectionAnchor,
    handleAutoCreateNoteGroup,
    handleBackToChat,
    handleBackToOverview,
    handleBackToReviewChat,
    handleBreadcrumbHome,
    handleCancelAutoJob,
    handleChatKeyDown,
    handleCheckSource,
    handleChipFilterSelect,
    handleConfirmDuplicateSource,
    handleCreateModuleFromWizard,
    handleCreateQuestionCard,
    handleCreateStudyCard,
    handleCreateSubjectFromWizard,
    handleDeleteAutoJob,
    handleDeleteModule,
    handleDeleteNoteGroup,
    handleDeleteQuestionCard,
    handleDeleteStudyCard,
    handleDeleteSubject,
    handleDeleteTopic,
    handleEditQuestionCard,
    handleEditStudyCard,
    handleGenerateNoteGroupMindMap,
    handleGenerateQuestions,
    handleModuleWizardSend,
    handleNoteGroupDragEnd,
    handleNoteGroupDragEnter,
    handleNoteGroupDragOver,
    handleNoteGroupDragStart,
    handleNoteGroupDrop,
    handleOpenMindMapTopic,
    handleOpenModuleWizard,
    handleOpenSubjectWizard,
    handleReadingModeChange,
    handleReadingTitleClick,
    handleReadingToggleMode,
    handleReadingViewInClean,
    handleRegenerateModuleNeedsReviewKnowledgeNodes,
    handleRegenerateNeedsReviewKnowledgeNodes,
    handleRegenerateTopicKnowledgeNodes,
    handleResetChipFilters,
    handleRetryAutoJob,
    handleReviewChatKeyDown,
    handleSaveMetadataTitle,
    handleSaveModuleMetadata,
    handleSaveQuestionCard,
    handleSaveStudyCard,
    handleSaveSubjectMetadata,
    handleSaveTopic,
    handleScrollNavToCard,
    handleSelectModule,
    handleSelectSubject,
    handleSendChat,
    handleSendReviewChat,
    handleSubjectUpdated,
    handleSubjectWizardSend,
    handleUniqueIdChange,
    handleUseGeneratedUniqueId,
    hasSidebar,
    includeDescendantStudyCards,
    isAdmin,
    isAdminPanelOpen,
    isChatOpen,
    isGeneratingQuestions,
    isMetadataOpen,
    isModuleMetadataOpen,
    isModuleWizardOpen,
    isQuestionCreateOpen,
    isQuestionFocusOpen,
    isQuestionPage,
    isReadingOpen,
    isReorderingNoteGroups,
    isRestoringRoute,
    isReviewOverlayVisible,
    isReviewing,
    isSourceReady,
    isStudyCreateOpen,
    isStudyPage,
    isSubjectManagementOpen,
    isSubjectMetadataOpen,
    isSubjectWizardOpen,
    isViewCardsPage,
    masteryFilter,
    metadataError,
    metadataSaving,
    metadataTitleDraft,
    mindMapDrilldown,
    moduleAdditionalInstructionsDraft,
    moduleDescriptionDraft,
    moduleDueCounts,
    moduleGenerationWorkflow,
    moduleGenerationWorkflowConnection,
    moduleGenerationWorkflowError,
    moduleGoalDraft,
    moduleMetadataError,
    moduleMetadataSaving,
    moduleMindMap,
    moduleMindMapError,
    moduleMindMapLoading,
    moduleNeedsReviewRegenerating,
    moduleNoteGroupStatsById,
    moduleNoteGroupsForDisplay,
    moduleQuestionTimeline,
    moduleScopeDraft,
    moduleStats,
    moduleStatsError,
    moduleStatsLoading,
    moduleTitleDraft,
    moduleWizardCreating,
    moduleWizardError,
    moduleWizardGoal,
    moduleWizardInput,
    moduleWizardLoading,
    moduleWizardMessages,
    moduleWizardScope,
    moduleWizardTitle,
    modules,
    navigate,
    navigateToNoteGroup,
    navigateToTopic,
    newQuestionCorrectIndices,
    newQuestionOptions,
    newQuestionPrompt,
    newQuestionRefs,
    newQuestionType,
    newStudyCardChipIds,
    newStudyCardContent,
    newStudyCardTitle,
    nextReviewCard,
    noteGroupCardTable,
    noteGroupCardTableError,
    noteGroupCardTableLoading,
    noteGroupChipIds,
    noteGroupMindMap,
    noteGroupMindMapError,
    noteGroupMindMapGenerating,
    noteGroupMindMapLoading,
    noteGroupMode,
    noteGroupNeedsReviewRegenerating,
    noteGroupProgress,
    noteGroupProgressError,
    noteGroupProgressLoading,
    noteGroupSource,
    noteGroupStats,
    noteGroupStatusMeta,
    openChatStudyCard,
    openMetadataModal,
    openModuleMetadataModal,
    openQuestionCreateModal,
    openQuestionFocus,
    openReviewStudyCard,
    openStudyCreateModal,
    openSubjectMetadataModal,
    pageBreadcrumbs,
    pageHeader,
    progressRange,
    questionCardError,
    questionCards,
    questionCardsForDisplay,
    questionJobStatus,
    questionTimeline,
    readingAvailable,
    readingContentRef,
    readingHighlights,
    readingHoverCardId,
    readingMode,
    readingPinnedCardId,
    requestReviewDelete,
    resolveConfirm,
    resolveNoteGroupLabel,
    reviewAnswer,
    reviewCardRefs,
    reviewCardType,
    reviewChatCardCache,
    reviewChatCardError,
    reviewChatCardId,
    reviewChatCardLoading,
    reviewChatError,
    reviewChatInput,
    reviewChatListRef,
    reviewChatLoading,
    reviewChatMessages,
    reviewChatView,
    reviewCount,
    reviewDeleteLoading,
    reviewDeleteStep,
    reviewError,
    reviewExplanationOpen,
    reviewFeedback,
    reviewIndex,
    reviewMode,
    reviewNoteGroupId,
    reviewQueue,
    reviewRefsMessage,
    reviewScope,
    reviewSummary,
    routeRestoreError,
    sectionNavItems,
    selectedModule,
    selectedModuleCode,
    selectedModuleId,
    selectedNoteGroup,
    selectedNoteGroupCode,
    selectedNoteGroupId,
    selectedNoteGroupWorkflow,
    selectedSubject,
    selectedSubjectCode,
    selectedSubjectId,
    selectedTopic,
    selectedTopicCode,
    selectedTopicId,
    setAutoAdditionalInstructions,
    setAutoRawText,
    setChatInput,
    setEditingQuestionCard,
    setEditingQuestionCardId,
    setEditingStudyCard,
    setEditingStudyCardId,
    setIncludeDescendantStudyCards,
    setIsAdminPanelOpen,
    setIsChatOpen,
    setIsMetadataOpen,
    setIsModuleMetadataOpen,
    setIsModuleWizardOpen,
    setIsQuestionCreateOpen,
    setIsReadingOpen,
    setIsStudyCreateOpen,
    setIsSubjectManagementOpen,
    setIsSubjectMetadataOpen,
    setIsSubjectWizardOpen,
    setMasteryFilter,
    setMetadataTitleDraft,
    setModuleAdditionalInstructionsDraft,
    setModuleDescriptionDraft,
    setModuleGoalDraft,
    setModuleScopeDraft,
    setModuleTitleDraft,
    setModuleWizardGoal,
    setModuleWizardInput,
    setModuleWizardScope,
    setModuleWizardTitle,
    setNewQuestionCorrectIndices,
    setNewQuestionOptions,
    setNewQuestionPrompt,
    setNewQuestionRefs,
    setNewQuestionType,
    setNewStudyCardChipIds,
    setNewStudyCardContent,
    setNewStudyCardTitle,
    setProgressRange,
    setReadingHoverCardId,
    setReadingPinnedCardId,
    setReviewChatInput,
    setReviewCount,
    setReviewSummary,
    setSubjectGoalDraft,
    setSubjectScopeDraft,
    setSubjectTitleDraft,
    setSubjectWizardGoal,
    setSubjectWizardInput,
    setSubjectWizardScope,
    setSubjectWizardTitle,
    setTopicDescriptionDraft,
    setTopicTitleDraft,
    shouldHoldSelectedNoteGroupContent,
    sidebarContent,
    sidebarError,
    sourceCheckError,
    sourceChecked,
    sourceChecking,
    sourceConfirmed,
    sourceDuplicateCount,
    sourceDuplicates,
    startReview,
    studyCardError,
    studyCardTitleById,
    studyCards,
    studyNoteSections,
    subjectGoalDraft,
    subjectMetadataError,
    subjectMetadataSaving,
    subjectScopeDraft,
    subjectTitleDraft,
    subjectWizardCreating,
    subjectWizardError,
    subjectWizardGoal,
    subjectWizardInput,
    subjectWizardLoading,
    subjectWizardMessages,
    subjectWizardScope,
    subjectWizardTitle,
    subjects,
    submitReviewAnswer,
    toggleReviewAnswer,
    topicCardTableRows,
    topicChips,
    topicDescriptionDraft,
    topicError,
    topicKnowledgeNodeRegenerating,
    topicKnowledgeNodeRegeneratingId,
    topicMindMap,
    topicMindMapError,
    topicMindMapLoading,
    topicSaving,
    topicTitleDraft,
    topicUnlinkedQuestionCount,
    wizardChatRef
  } = model;

  return <>
      <StudyAppReviewOverlay model={model} />
      <StudyAppTutorChatOverlay model={model} />
      <StudyAppReadingDialog model={model} />
      <StudyAppGlobalDialogs model={model} />
      <StudyAppMainContent model={model} />
      <ConfirmActionDialog
        open={Boolean(confirmAction)}
        title={confirmAction?.title || ""}
        description={confirmAction?.description || ""}
        confirmLabel={confirmAction?.confirmLabel || "Confirm"}
        onOpenChange={(open) => {
          if (!open) {
            resolveConfirm(false);
          }
        }}
        onConfirm={() => resolveConfirm(true)}
      />
      <Toaster position="bottom-right" richColors />
    </>;
}
